name: Generate_xml_sitemap

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "sitemap_job"
  sitemap_job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Generate a sitemap

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout the repo
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 

    - name: Generate the sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://lewis-chinery.github.io/

    # Runs a set of commands using the runners shell
    - name: Output stats
      run: |
        echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
        echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
        echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"
    
    - name: Commit and push
      run: |
        git add sitemap.xml
        git commit -m "Automated sitemap update" sitemap.xml
        git push
